### ISSUE TITLE
Node version locked

### ISSUE THREAD

**Issue by ShaunLWM** [leocabeza/the-movie-db#12]
Hi,

I just found this node module for a project that I'll be creating. However upon installation, I realized that the node engine is locked to 10.13. May I know if there's any specific reason why?

https://github.com/leocabeza/the-movie-db/blob/master/package.json#L43

Thank you!

**Comment by leocabeza** [comment]
Originally it was thought for keeping package-lock.json diff consistent if more collaborators wanted to contribute.

I just published a change supporting node v8.6.0 and up, @ShaunLWM

**Comment by ShaunLWM** [comment]
Thanks for the quick updates!

However after installation, I am unable to run the module.
`yarn add @leonardocabeza/the-movie-db` install the package but with only 3 files `LICENSE, package.json & README.md`.
`yarn add https://github.com/leocabeza/the-movie-db` installs the full package but got the `Cannot find module '@leonardocabeza/the-movie-db'` error.
I tried changing directory into the package and using webpack to compile but got `TypeError: TheMovieDb is not a constructor`.

Is there something that I'm doing wrong?

Thank you!

**Comment by leocabeza** [comment]
Sorry for the delay, but this was a weird one. Could you try v2.1.10 version now? @ShaunLWM

**Comment by ShaunLWM** [comment]
It's working well now. Thank you so much for the updates! Appreciate it.
