### ISSUE TITLE
Typo in Docs.

### ISSUE THREAD

**Issue by dunklesToast** [leocabeza/the-movie-db#54]
In the v3 docs, the module is named `movies`. In the source, the file is named `movie` and is exported as such. Therefore the module has to be renamed in the docs. Since I am not sure, if the docs are autogenerate, I haven't added a PR yet.

https://github.com/leocabeza/the-movie-db/blob/master/docs/v3-api.md#module_movies

Example:
```js
let details = await tmdb.movie.details(384018);
```
works.
```js
let details = await tmdb.movies.details(384018);
```
is not defined.

This should be changed in the docs and not in the code since it would be a breaking change.

**Comment by leocabeza** [comment]
Hi @dunklesToast, nice catch, it's an error on my side in: https://github.com/leocabeza/the-movie-db/blob/master/src/entities/v3/movie.js#L5

Docs are generated when running the next command: `npm run docs:v3
`

**Comment by leocabeza** [comment]
This should be closed in https://github.com/leocabeza/the-movie-db/releases/tag/v3.0.8, feel free to open a new issue if you find a bug again.
