### ISSUE TITLE
Module strips out additional options which are needed when append_to_response is used.

### ISSUE THREAD

**Issue by dunklesToast** [leocabeza/the-movie-db#55]
The module ignores the fact, that with the `append_to_response` option, other options can be passed which are not described for that specific route.

Example:
```
const details = await tmdb.movie.details(content.id, {
    language: 'de-DE',
    append_to_response: 'credits,images',
    include_image_language: 'de,en,null'
});
```
won't pass the `include_image_language` option because it's being ignored [here](https://github.com/leocabeza/the-movie-db/blob/master/src/entities/v3/movie.js#L133).

**Comment by leocabeza** [comment]
You are right, I've added whitelisted that option on movie detail, tv show detail, tv season detail, tv episode detail and person detail as described here: https://developers.themoviedb.org/3/getting-started/append-to-response.

This should be closed in https://github.com/leocabeza/the-movie-db/releases/tag/v3.0.8, feel free to open a new issue if you find a bug again.
