### ISSUE TITLE
Missing accessToken paramter for the list.details function (v4)

### ISSUE THREAD

**Issue by amcarthur** [leocabeza/the-movie-db#65]
It appears that the function **details** for the **list** object for the v4 API is missing the _accessToken_ parameter.

https://github.com/leocabeza/the-movie-db/blob/master/src/entities/v4/list.js#L113

**Comment by leocabeza** [comment]
You are right, I'll take a look soon, but I don't mind if you want to make a PR yourself. The fix should be similar to what's in https://github.com/leocabeza/the-movie-db/blob/master/src/entities/v4/list.js#L138

**Comment by amcarthur** [comment]
I was going to, but I was a little confused because that API endpoint doesn’t require an access token, just an API key (unless you are trying to access a private list). I noticed that you require an access token for other methods that may not need an access token. Is it idiomatic now with their v4 API to always pass an access token, or was this a design choice by you to keep things simpler and consistent?

**Comment by leonardo-globant** [comment]
I just assumed that whoever used these methods was trying to access another user's private data. Do you have a different use case?

I'm going to push a new version fixing this

**Comment by leocabeza** [comment]
I just assumed that whoever used these methods was trying to access another user's private data. Do you have a different use case?

I'm going to push a new version fixing this
