### ISSUE TITLE
trending.items() results in internal server error

### ISSUE THREAD

**Issue by freddieerg** [leocabeza/the-movie-db#75]
**Describe the bug**
Attempting to use trending.items() with any combination of possible options will result in an internal server error.
 
**To Reproduce**

MY_API_KEY = My actual API key, confirmed working using other methods.

```
let {v3} = require('@leonardocabeza/the-movie-db');

const mdb = v3('MY_API_KEY');

async function tester() {
    let r = await mdb.trending.items({
        media_type: 'all',
        time_window: 'day',
    });
    return r
}

tester().then(r => {
    console.log(r)
})

```
**Expected behavior**
Should return a JSON of trending media items of all types for the last 24 hrs. (Same error occurs for any option however).

**Desktop (please complete the following information):**
 - Node Version 13.11

**Additional context**
Please could you also add a page option as this is supported for trending but not sure it's implemented?

**Comment by leocabeza** [comment]
Hi @freddieerg, thanks for reporting the error.

After inspecting, it was a typo on my side, but this has been fixed in version 4.0.7. As for the options supported for this method, you can see them in: https://github.com/leocabeza/the-movie-db/blob/master/docs/v3-api.md#trendingitems--promise
