### ISSUE TITLE
missing dist assets in nodejs

### ISSUE THREAD

**Issue by bubkoo** [leocabeza/the-movie-db#81]
**Describe the bug**

Missing the `dist` assets in nodejs. Should include the `dist` dir when `npm publish`

![image](https://user-images.githubusercontent.com/6045824/132167383-735e70ce-2ae2-4f69-8e8a-9a7a332a6ec3.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leocabeza** [comment]
Thank you for reporting this bug @bubkoo, It's been fixed on the latest release: https://github.com/leocabeza/the-movie-db/releases/tag/v4.5.0
